# Generated by Django 3.1.1 on 2020-09-09 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created Date')),
                ('created_by', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Created By')),
                ('modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Modified Date')),
                ('modified_by', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Modified By')),
                ('status', models.CharField(choices=[('new', 'New Order'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10, verbose_name='Order Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
