# Generated by Django 3.1.1 on 2020-09-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=1000, null=True, verbose_name='Price'),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(null=True, verbose_name='Quantity'),
        ),
        migrations.AddField(
            model_name='order',
            name='symbol',
            field=models.CharField(max_length=50, null=True, verbose_name='Stock Symbol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'New Order'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='new', max_length=10, null=True, verbose_name='Order Status'),
        ),
    ]
