# Generated by Django 3.1.1 on 2020-09-10 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200910_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=150, null=True, verbose_name='Name'),
        ),
    ]
