# Generated by Django 3.1.1 on 2020-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200910_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='status',
            field=models.CharField(choices=[('new', 'New Order'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='new', max_length=10, null=True, verbose_name='Order Status'),
        ),
    ]
