# Generated by Django 3.1.1 on 2020-09-10 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200910_1903'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatus',
            options={'ordering': ['-modified_date']},
        ),
    ]
